"""add_client_credit_controls

Revision ID: 5a738ca825b4
Revises: d6b8157ca968
Create Date: 2026-07-24 21:32:17.116181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a738ca825b4'
down_revision: Union[str, None] = 'd6b8157ca968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if columns already exist in PostgreSQL
    columns_clients = [col['name'] for col in inspector.get_columns('clients')]
    columns_orders = [col['name'] for col in inspector.get_columns('orders')]
    
    if 'allows_credit' not in columns_clients:
        op.add_column('clients', sa.Column('allows_credit', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    if 'payment_terms' not in columns_clients:
        op.add_column('clients', sa.Column('payment_terms', sa.Integer(), nullable=False, server_default=sa.text('0')))
    if 'due_date' not in columns_orders:
        op.add_column('orders', sa.Column('due_date', sa.Date(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'due_date')
    op.drop_column('clients', 'payment_terms')
    op.drop_column('clients', 'allows_credit')
    # ### end Alembic commands ###
